package it.iiscastelli.pwdmgr.ui;

public class DialogValutaComplessita extends javax.swing.JDialog {

    /**
     * Creates new form DialogNuovaPassword
     */
    public DialogValutaComplessita(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        _lblPassword = new javax.swing.JLabel();
        pnlPassword = new javax.swing.JPanel();
        pnlPwdPassword = new javax.swing.JPanel();
        pwdPassword = new javax.swing.JPasswordField();
        btnMostra = new javax.swing.JButton();
        pnlTxtPassword = new javax.swing.JPanel();
        txtPassword = new javax.swing.JTextField();
        btnNascondi = new javax.swing.JButton();
        _lblComplessita = new javax.swing.JLabel();
        _pbComplessita = new javax.swing.JProgressBar();
        lblComplessita = new javax.swing.JLabel();
        btnChiudi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        _lblPassword.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        _lblPassword.setText("Password");

        pnlPassword.setLayout(new javax.swing.OverlayLayout(pnlPassword));

        pwdPassword.setText("jPasswordField1");

        btnMostra.setBackground(new java.awt.Color(13, 110, 253));
        btnMostra.setForeground(new java.awt.Color(255, 255, 255));
        btnMostra.setText("Mostra");
        btnMostra.setBorderPainted(false);
        btnMostra.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout pnlPwdPasswordLayout = new javax.swing.GroupLayout(pnlPwdPassword);
        pnlPwdPassword.setLayout(pnlPwdPasswordLayout);
        pnlPwdPasswordLayout.setHorizontalGroup(
            pnlPwdPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPwdPasswordLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(pwdPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMostra, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlPwdPasswordLayout.setVerticalGroup(
            pnlPwdPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPwdPasswordLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(pnlPwdPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pwdPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMostra))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pnlPassword.add(pnlPwdPassword);

        txtPassword.setToolTipText("");

        btnNascondi.setBackground(new java.awt.Color(13, 110, 253));
        btnNascondi.setForeground(new java.awt.Color(255, 255, 255));
        btnNascondi.setText("Nascondi");
        btnNascondi.setBorderPainted(false);
        btnNascondi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout pnlTxtPasswordLayout = new javax.swing.GroupLayout(pnlTxtPassword);
        pnlTxtPassword.setLayout(pnlTxtPasswordLayout);
        pnlTxtPasswordLayout.setHorizontalGroup(
            pnlTxtPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTxtPasswordLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNascondi)
                .addGap(0, 0, 0))
        );
        pnlTxtPasswordLayout.setVerticalGroup(
            pnlTxtPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTxtPasswordLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(pnlTxtPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNascondi))
                .addGap(0, 0, 0))
        );

        pnlPassword.add(pnlTxtPassword);

        _lblComplessita.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        _lblComplessita.setText("Complessità");

        _pbComplessita.setForeground(new java.awt.Color(25, 135, 84));
        _pbComplessita.setValue(50);

        lblComplessita.setText("Molto debole");

        btnChiudi.setBackground(new java.awt.Color(108, 117, 125));
        btnChiudi.setForeground(new java.awt.Color(255, 255, 255));
        btnChiudi.setText("Chiudi");
        btnChiudi.setBorderPainted(false);
        btnChiudi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnChiudi)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(_lblPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(_lblComplessita)
                        .addComponent(pnlPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(_pbComplessita, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblComplessita)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(_lblPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(_lblComplessita)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblComplessita, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(_pbComplessita, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnChiudi)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogValutaComplessita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogValutaComplessita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogValutaComplessita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogValutaComplessita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogValutaComplessita dialog = new DialogValutaComplessita(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel _lblComplessita;
    private javax.swing.JLabel _lblPassword;
    private javax.swing.JProgressBar _pbComplessita;
    private javax.swing.JButton btnChiudi;
    private javax.swing.JButton btnMostra;
    private javax.swing.JButton btnNascondi;
    private javax.swing.JLabel lblComplessita;
    private javax.swing.JPanel pnlPassword;
    private javax.swing.JPanel pnlPwdPassword;
    private javax.swing.JPanel pnlTxtPassword;
    private javax.swing.JPasswordField pwdPassword;
    private javax.swing.JTextField txtPassword;
    // End of variables declaration//GEN-END:variables
}
