package it.iiscastelli.pwdmgr.ui;

import it.iiscastelli.pwdmgr.model.Credenziali;
import it.iiscastelli.pwdmgr.util.GestoreMessaggi;

public class DialogNuoveCredenziali extends javax.swing.JDialog {

    private FramePrincipale padre;
    private String sitoApp;
    private String usernameEmail;
    private Credenziali credenziali;
    
    /**
     * Creates new form DialogNuoveCredenziali
     */
    public DialogNuoveCredenziali(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        padre = (FramePrincipale) parent;
    }
    
    private void inizializza() {
        sitoApp = "";
        usernameEmail = "";
        credenziali = new Credenziali(sitoApp, usernameEmail);
    }

    public void setCredenziali(Credenziali credenziali) {
        this.credenziali = credenziali;
        txtSitoApp.setText(credenziali.getSitoApp());
        txtUsernameEmail.setText(credenziali.getUsernameEmail());
    }
    
    private boolean controllaCampi() {
        sitoApp = txtSitoApp.getText();
        usernameEmail = txtUsernameEmail.getText();
        return !sitoApp.isBlank() && !usernameEmail.isBlank();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        _lblSitoApp = new javax.swing.JLabel();
        txtSitoApp = new javax.swing.JTextField();
        _lblUsernameEmail = new javax.swing.JLabel();
        txtUsernameEmail = new javax.swing.JTextField();
        btnChiudi = new javax.swing.JButton();
        btnAvanti = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nuove credenziali");

        _lblSitoApp.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        _lblSitoApp.setText("Sito / App");

        _lblUsernameEmail.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        _lblUsernameEmail.setText("Username / Email");

        btnChiudi.setBackground(new java.awt.Color(108, 117, 125));
        btnChiudi.setForeground(new java.awt.Color(255, 255, 255));
        btnChiudi.setText("Chiudi");
        btnChiudi.setBorderPainted(false);
        btnChiudi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnChiudi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChiudiActionPerformed(evt);
            }
        });

        btnAvanti.setBackground(new java.awt.Color(13, 110, 253));
        btnAvanti.setForeground(new java.awt.Color(255, 255, 255));
        btnAvanti.setText("Avanti");
        btnAvanti.setBorderPainted(false);
        btnAvanti.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAvanti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvantiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(_lblSitoApp, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(_lblUsernameEmail, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtUsernameEmail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                    .addComponent(txtSitoApp, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnChiudi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAvanti)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(_lblSitoApp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSitoApp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(_lblUsernameEmail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUsernameEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAvanti)
                    .addComponent(btnChiudi))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnChiudiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChiudiActionPerformed
        dispose();
    }//GEN-LAST:event_btnChiudiActionPerformed

    private void btnAvantiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvantiActionPerformed
        boolean campiValorizzati = controllaCampi();
        if(!campiValorizzati) {
            GestoreMessaggi.mostraErrore(this, "Devi compilare tutti i campi");
            return;
        }
        credenziali = new Credenziali(sitoApp, usernameEmail);
        DialogNuovaPassword dialog = new DialogNuovaPassword(padre, true);
        dialog.setCredenziali(credenziali);
        dispose();
        dialog.setVisible(true);
    }//GEN-LAST:event_btnAvantiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogNuoveCredenziali.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogNuoveCredenziali.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogNuoveCredenziali.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogNuoveCredenziali.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogNuoveCredenziali dialog = new DialogNuoveCredenziali(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel _lblSitoApp;
    private javax.swing.JLabel _lblUsernameEmail;
    private javax.swing.JButton btnAvanti;
    private javax.swing.JButton btnChiudi;
    private javax.swing.JTextField txtSitoApp;
    private javax.swing.JTextField txtUsernameEmail;
    // End of variables declaration//GEN-END:variables
}
