package it.iiscastelli.pwdmgr.ui;

import it.iiscastelli.pwdmgr.config.Colore;
import it.iiscastelli.pwdmgr.model.ValutatoreComplessita;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

public class DialogValutaComplessita extends javax.swing.JDialog {

    private static final int SOGLIA_MOLTO_DEBOLE = ValutatoreComplessita.SOGLIA_MOLTO_DEBOLE;
    private static final int SOGLIA_DEBOLE = ValutatoreComplessita.SOGLIA_DEBOLE;
    private static final int SOGLIA_BUONA = ValutatoreComplessita.SOGLIA_BUONA;
    private static final int SOGLIA_MOLTO_BUONA = ValutatoreComplessita.SOGLIA_MOLTO_BUONA;
    private static final int SOGLIA_FORTE = ValutatoreComplessita.SOGLIA_FORTE;
    
    private static final String TESTO_MOLTO_DEBOLE = ValutatoreComplessita.TESTO_MOLTO_DEBOLE;
    private static final String TESTO_DEBOLE = ValutatoreComplessita.TESTO_DEBOLE;
    private static final String TESTO_BUONA = ValutatoreComplessita.TESTO_BUONA;
    private static final String TESTO_MOLTO_BUONA = ValutatoreComplessita.TESTO_MOLTO_BUONA;
    private static final String TESTO_FORTE = ValutatoreComplessita.TESTO_FORTE;
    private static final String TESTO_MOLTO_FORTE = ValutatoreComplessita.TESTO_MOLTO_FORTE;
    
    private ValutatoreComplessita valutatore;
    private String password;
    
    /**
     * Creates new form DialogNuovaPassword
     */
    public DialogValutaComplessita(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        inizializza();
    }
    
    private void inizializza() {
        password = "";
        valutatore = new ValutatoreComplessita(password);
        pbComplessita.setValue(0);
        lblComplessita.setVisible(false);
        nascondiPassword();
    }
    
    private void mostraPassword() {
        pnlPwdPassword.setVisible(false);
        pnlTxtPassword.setVisible(true);
        txtPassword.requestFocus();
        txtPassword.setText(password);
        txtPassword.select(password.length(), password.length());
    }
    
    private void nascondiPassword() {
        pnlTxtPassword.setVisible(false);
        pnlPwdPassword.setVisible(true);
        pwdPassword.requestFocus();
        pwdPassword.setText(password);
        pwdPassword.select(password.length(), password.length());
    }
    
    private void valutaComplessita() {
        int punteggio = valutatore.valuta();
        pbComplessita.setValue(punteggio);
        aggiornaColoreProgressBar();
        aggiornaTestoComplessita();
    }
    
    private void aggiornaColoreProgressBar() {
        int valore = pbComplessita.getValue();
        if(valore <= SOGLIA_MOLTO_DEBOLE) {
            pbComplessita.setForeground(Colore.RED);
        } else if(valore <= SOGLIA_DEBOLE) {
            pbComplessita.setForeground(Colore.ORANGE);
        } else if(valore <= SOGLIA_BUONA) {
            pbComplessita.setForeground(Colore.YELLOW);
        } else if(valore <= SOGLIA_MOLTO_BUONA) {
            pbComplessita.setForeground(Colore.GREEN);
        } else if(valore <= SOGLIA_FORTE) {
            pbComplessita.setForeground(Colore.TEAL);
        } else {
            pbComplessita.setForeground(Colore.CYAN);
        }
    }
    
    private void aggiornaTestoComplessita() {
        int valore = pbComplessita.getValue();
        lblComplessita.setVisible(!password.isEmpty());
        if(valore <= SOGLIA_MOLTO_DEBOLE) {
            lblComplessita.setText(TESTO_MOLTO_DEBOLE);
        } else if(valore <= SOGLIA_DEBOLE) {
            lblComplessita.setText(TESTO_DEBOLE);
        } else if(valore <= SOGLIA_BUONA) {
            lblComplessita.setText(TESTO_BUONA);
        } else if(valore <= SOGLIA_MOLTO_BUONA) {
            lblComplessita.setText(TESTO_MOLTO_BUONA);
        } else if(valore <= SOGLIA_FORTE) {
            lblComplessita.setText(TESTO_FORTE);
        } else {
            lblComplessita.setText(TESTO_MOLTO_FORTE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        _lblPassword = new javax.swing.JLabel();
        pnlPassword = new javax.swing.JPanel();
        pnlPwdPassword = new javax.swing.JPanel();
        pwdPassword = new javax.swing.JPasswordField();
        btnMostra = new javax.swing.JButton();
        pnlTxtPassword = new javax.swing.JPanel();
        txtPassword = new javax.swing.JTextField();
        btnNascondi = new javax.swing.JButton();
        _lblComplessita = new javax.swing.JLabel();
        pbComplessita = new javax.swing.JProgressBar();
        lblComplessita = new javax.swing.JLabel();
        btnChiudi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Valutazione complessità password");
        setResizable(false);

        _lblPassword.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        _lblPassword.setText("Password");

        pnlPassword.setLayout(new javax.swing.OverlayLayout(pnlPassword));

        pwdPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPasswordKeyReleased(evt);
            }
        });

        btnMostra.setBackground(new java.awt.Color(13, 110, 253));
        btnMostra.setForeground(new java.awt.Color(255, 255, 255));
        btnMostra.setText("Mostra");
        btnMostra.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMostra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlPwdPasswordLayout = new javax.swing.GroupLayout(pnlPwdPassword);
        pnlPwdPassword.setLayout(pnlPwdPasswordLayout);
        pnlPwdPasswordLayout.setHorizontalGroup(
            pnlPwdPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPwdPasswordLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(pwdPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMostra, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        pnlPwdPasswordLayout.setVerticalGroup(
            pnlPwdPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPwdPasswordLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(pnlPwdPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pwdPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMostra)))
        );

        pnlPassword.add(pnlPwdPassword);

        txtPassword.setToolTipText("");
        txtPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPasswordKeyReleased(evt);
            }
        });

        btnNascondi.setBackground(new java.awt.Color(13, 110, 253));
        btnNascondi.setForeground(new java.awt.Color(255, 255, 255));
        btnNascondi.setText("Nascondi");
        btnNascondi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNascondi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNascondiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlTxtPasswordLayout = new javax.swing.GroupLayout(pnlTxtPassword);
        pnlTxtPassword.setLayout(pnlTxtPasswordLayout);
        pnlTxtPasswordLayout.setHorizontalGroup(
            pnlTxtPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTxtPasswordLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNascondi)
                .addGap(0, 0, 0))
        );
        pnlTxtPasswordLayout.setVerticalGroup(
            pnlTxtPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTxtPasswordLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(pnlTxtPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNascondi))
                .addGap(0, 0, 0))
        );

        pnlPassword.add(pnlTxtPassword);

        _lblComplessita.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        _lblComplessita.setText("Complessità");

        pbComplessita.setForeground(new java.awt.Color(25, 135, 84));
        pbComplessita.setValue(50);

        lblComplessita.setText("Molto debole");

        btnChiudi.setBackground(new java.awt.Color(108, 117, 125));
        btnChiudi.setForeground(new java.awt.Color(255, 255, 255));
        btnChiudi.setText("Chiudi");
        btnChiudi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnChiudi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChiudiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(_lblPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(_lblComplessita)
                    .addComponent(pnlPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pbComplessita, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblComplessita, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnChiudi)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(_lblPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(_lblComplessita)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblComplessita, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pbComplessita, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnChiudi)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnChiudiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChiudiActionPerformed
        dispose();
    }//GEN-LAST:event_btnChiudiActionPerformed

    private void btnNascondiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNascondiActionPerformed
        nascondiPassword();
    }//GEN-LAST:event_btnNascondiActionPerformed

    private void txtPasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPasswordKeyReleased
        Object source = evt.getSource();
        if(source instanceof JPasswordField) {
            password = new String(pwdPassword.getPassword());
            txtPassword.setText(password);
        } else if(source instanceof JTextField) {
            password = txtPassword.getText();
            pwdPassword.setText(password);
        }
        valutatore.setPassword(password);
        valutaComplessita();
    }//GEN-LAST:event_txtPasswordKeyReleased

    private void btnMostraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostraActionPerformed
        mostraPassword();
    }//GEN-LAST:event_btnMostraActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel _lblComplessita;
    private javax.swing.JLabel _lblPassword;
    private javax.swing.JButton btnChiudi;
    private javax.swing.JButton btnMostra;
    private javax.swing.JButton btnNascondi;
    private javax.swing.JLabel lblComplessita;
    private javax.swing.JProgressBar pbComplessita;
    private javax.swing.JPanel pnlPassword;
    private javax.swing.JPanel pnlPwdPassword;
    private javax.swing.JPanel pnlTxtPassword;
    private javax.swing.JPasswordField pwdPassword;
    private javax.swing.JTextField txtPassword;
    // End of variables declaration//GEN-END:variables
}
