package it.iiscastelli.pwdmgr.ui;

public class DialogGeneraPassword extends javax.swing.JDialog {

    /**
     * Creates new form DialogNuovaPassword
     */
    public DialogGeneraPassword(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngrpTipologia = new javax.swing.ButtonGroup();
        _lblTipologia = new javax.swing.JLabel();
        btnManuale = new javax.swing.JRadioButton();
        btnCasuale = new javax.swing.JRadioButton();
        _lblPassword = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        btnCopia = new javax.swing.JButton();
        _lblComplessita = new javax.swing.JLabel();
        _pbComplessita = new javax.swing.JProgressBar();
        lblComplessita = new javax.swing.JLabel();
        pnlConfigurazione = new javax.swing.JPanel();
        txtLunghezza = new javax.swing.JTextField();
        _lblLunghezza = new javax.swing.JLabel();
        sldLunghezza = new javax.swing.JSlider();
        _lblSceltaCaratteri = new javax.swing.JLabel();
        chkMaiuscole = new javax.swing.JCheckBox();
        chkCifre = new javax.swing.JCheckBox();
        chkMinuscole = new javax.swing.JCheckBox();
        chkSimboli = new javax.swing.JCheckBox();
        btnChiudi = new javax.swing.JButton();
        btnSalva = new javax.swing.JButton();
        btnGenera = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        _lblTipologia.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        _lblTipologia.setText("Tipologia");

        btngrpTipologia.add(btnManuale);
        btnManuale.setText("Manuale");

        btngrpTipologia.add(btnCasuale);
        btnCasuale.setSelected(true);
        btnCasuale.setText("Casuale");

        _lblPassword.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        _lblPassword.setText("Password");

        txtPassword.setToolTipText("");

        btnCopia.setBackground(new java.awt.Color(13, 110, 253));
        btnCopia.setForeground(new java.awt.Color(255, 255, 255));
        btnCopia.setText("Copia negli appunti");
        btnCopia.setBorderPainted(false);
        btnCopia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        _lblComplessita.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        _lblComplessita.setText("Complessità");

        _pbComplessita.setForeground(new java.awt.Color(25, 135, 84));
        _pbComplessita.setValue(50);

        lblComplessita.setText("Normale");

        _lblLunghezza.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        _lblLunghezza.setText("Lunghezza");

        sldLunghezza.setForeground(new java.awt.Color(13, 110, 253));

        _lblSceltaCaratteri.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        _lblSceltaCaratteri.setText("Scelta caratteri");

        chkMaiuscole.setSelected(true);
        chkMaiuscole.setText("Maiuscole");

        chkCifre.setSelected(true);
        chkCifre.setText("Cifre");

        chkMinuscole.setSelected(true);
        chkMinuscole.setText("Minuscole");

        chkSimboli.setSelected(true);
        chkSimboli.setText("Simboli");

        javax.swing.GroupLayout pnlConfigurazioneLayout = new javax.swing.GroupLayout(pnlConfigurazione);
        pnlConfigurazione.setLayout(pnlConfigurazioneLayout);
        pnlConfigurazioneLayout.setHorizontalGroup(
            pnlConfigurazioneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlConfigurazioneLayout.createSequentialGroup()
                .addComponent(sldLunghezza, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtLunghezza, javax.swing.GroupLayout.PREFERRED_SIZE, 46, Short.MAX_VALUE))
            .addGroup(pnlConfigurazioneLayout.createSequentialGroup()
                .addComponent(_lblLunghezza, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlConfigurazioneLayout.createSequentialGroup()
                .addGroup(pnlConfigurazioneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(chkCifre, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkMaiuscole, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(_lblSceltaCaratteri))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlConfigurazioneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkMinuscole, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkSimboli, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlConfigurazioneLayout.setVerticalGroup(
            pnlConfigurazioneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlConfigurazioneLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(_lblLunghezza)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlConfigurazioneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sldLunghezza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLunghezza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(_lblSceltaCaratteri)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlConfigurazioneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkMaiuscole)
                    .addComponent(chkMinuscole))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlConfigurazioneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkCifre)
                    .addComponent(chkSimboli))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        btnChiudi.setBackground(new java.awt.Color(108, 117, 125));
        btnChiudi.setForeground(new java.awt.Color(255, 255, 255));
        btnChiudi.setText("Chiudi");
        btnChiudi.setBorderPainted(false);
        btnChiudi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnSalva.setBackground(new java.awt.Color(25, 135, 84));
        btnSalva.setForeground(new java.awt.Color(255, 255, 255));
        btnSalva.setText("Salva");
        btnSalva.setBorderPainted(false);
        btnSalva.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnGenera.setBackground(new java.awt.Color(13, 110, 253));
        btnGenera.setForeground(new java.awt.Color(255, 255, 255));
        btnGenera.setText("Genera");
        btnGenera.setBorderPainted(false);
        btnGenera.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCopia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGenera))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnManuale, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCasuale, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(_lblTipologia)
                            .addComponent(_lblPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(_lblComplessita)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(_pbComplessita, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblComplessita))
                            .addComponent(pnlConfigurazione, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnChiudi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSalva)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(_lblTipologia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnManuale)
                    .addComponent(btnCasuale))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(_lblPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCopia)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGenera))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(_lblComplessita)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblComplessita, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(_pbComplessita, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlConfigurazione, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalva)
                    .addComponent(btnChiudi))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogGeneraPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogGeneraPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogGeneraPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogGeneraPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogGeneraPassword dialog = new DialogGeneraPassword(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel _lblComplessita;
    private javax.swing.JLabel _lblLunghezza;
    private javax.swing.JLabel _lblPassword;
    private javax.swing.JLabel _lblSceltaCaratteri;
    private javax.swing.JLabel _lblTipologia;
    private javax.swing.JProgressBar _pbComplessita;
    private javax.swing.JRadioButton btnCasuale;
    private javax.swing.JButton btnChiudi;
    private javax.swing.JButton btnCopia;
    private javax.swing.JButton btnGenera;
    private javax.swing.JRadioButton btnManuale;
    private javax.swing.JButton btnSalva;
    private javax.swing.ButtonGroup btngrpTipologia;
    private javax.swing.JCheckBox chkCifre;
    private javax.swing.JCheckBox chkMaiuscole;
    private javax.swing.JCheckBox chkMinuscole;
    private javax.swing.JCheckBox chkSimboli;
    private javax.swing.JLabel lblComplessita;
    private javax.swing.JPanel pnlConfigurazione;
    private javax.swing.JSlider sldLunghezza;
    private javax.swing.JTextField txtLunghezza;
    private javax.swing.JTextField txtPassword;
    // End of variables declaration//GEN-END:variables
}
